In [1]:
import pandas as pd

In [2]:
df_companies = pd.read_excel(
    "../data/raw/companies.xlsx",
    header=1
)

print(df_companies.shape)
print(df_companies.columns.tolist())

df_companies.head()

(92, 12)
['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,67.0,96.5,14.70
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd\n,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2.0,265.0,12.9,18.10

In [3]:
df_pl = pd.read_excel(
    "../data/raw/profitandloss.xlsx",
    header=1
)

print(df_pl.shape)
print(df_pl.columns.tolist())

df_pl.head()

(1276, 15)
['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,1653,1451,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0
1,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0
2,63,ABB,Mar 2015,2289,1977,312.0,14.0,48,0,15,344,34.0,229,108.0,29.0
3,64,ABB,Mar 2016,2614,2250,365.0,14.0,50,3,14,398,36.0,255,120.0,29.0
4,65,ABB,Mar 2017,2903,2505,398.0,14.0,57,2,16,436,37.0,277,130.0,31.0

In [4]:
df_pl["year"].unique()

array(['Dec 2012', 'Mar 2014', 'Mar 2015', 'Mar 2016', 'Mar 2017',
       'Mar 2018', 'Mar 2019', 'Mar 2020', 'Mar 2021', 'Mar 2022',
       'Mar 2023', 'Mar 2024', 'TTM', 'Mar 2013', 'Dec 2013', 'Dec 2014',
       'Dec 2015', 'Dec 2016', 'Dec 2017', 'Dec 2018', 'Dec 2019',
       'Dec 2020', 'Dec 2021', 'Mar 2023 15', 'Jun 2013', 'Jun 2014',
       'Jun 2015', 'Mar 2016 9m', 'Mar 2011', 'Mar 2012', 'Dec 2022',
       'Dec 2023', 'Sep 2011', 'Sep 2014', 'Sep 2015', 'Sep 2016',
       'Sep 2017', 'Sep 2018', 'Sep 2019', 'Sep 2020', 'Sep 2021',
       'Sep 2022', 'Sep 2023', 'Sep 2024'], dtype=object)

In [5]:
print(df_companies.columns.tolist())

['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

In [6]:
df_companies[["company_name", "nse_profile", "bse_profile"]].head()

,company_name,nse_profile,bse_profile
0,Abbott India Ltd,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...
1,Adani Energy Solutions Ltd,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...
2,Adani Enterprises Ltd,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...
3,Adani Green Energy Ltd,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...
4,Adani Ports & Special Economic Zone Ltd\n,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...

In [12]:
df = pd.read_excel("../data/supporting/stock_prices.xlsx")
print(df.columns.tolist())

['id', 'company_id', 'date', 'open_price', 'high_price', 'low_price', 'close_price', 'volume', 'adjusted_close']

In [13]:
df = pd.read_excel("../data/supporting/financial_ratios.xlsx")
print(df.columns.tolist())

['id', 'company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr']

In [14]:
df = pd.read_excel("../data/supporting/market_cap.xlsx")
print(df.columns.tolist())

['id', 'company_id', 'year', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct']

In [15]:
df = pd.read_excel("../data/raw/profitandloss.xlsx", header=1)
print(df.columns.tolist())
df.head()

['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,61,ABB,Dec 2012,1653,1451,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0
1,62,ABB,Mar 2014,2276,2009,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0
2,63,ABB,Mar 2015,2289,1977,312.0,14.0,48,0,15,344,34.0,229,108.0,29.0
3,64,ABB,Mar 2016,2614,2250,365.0,14.0,50,3,14,398,36.0,255,120.0,29.0
4,65,ABB,Mar 2017,2903,2505,398.0,14.0,57,2,16,436,37.0,277,130.0,31.0

In [16]:
print(df["year"].head())

0    Dec 2012
1    Mar 2014
2    Mar 2015
3    Mar 2016
4    Mar 2017
Name: year, dtype: object

In [17]:
df = pd.read_excel("../data/raw/balancesheet.xlsx", header=1)

print(df.columns.tolist())

['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']

In [18]:
import pandas as pd

files = [
    "cashflow.xlsx",
    "analysis.xlsx",
    "documents.xlsx",
    "prosandcons.xlsx"
]

for file in files:
    df = pd.read_excel(f"../data/raw/{file}", header=1)
    print("\n", file)
    print(df.columns.tolist())
    print(df.shape)

 cashflow.xlsx
['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']
(1187, 7)

 analysis.xlsx
['id', 'company_id', 'compounded_sales_growth', 'compounded_profit_growth', 'stock_price_cagr', 'roe']
(20, 6)

 documents.xlsx
['id', 'company_id', 'Year', 'Annual_Report']
(1585, 4)

 prosandcons.xlsx
['id', 'company_id', 'pros', 'cons']
(16, 4)

In [2]:
import pandas as pd

df = pd.read_excel("../data/raw/profitandloss.xlsx", header=1)

dup = df[df.duplicated(subset=["company_id", "year"], keep=False)]
print("Duplicate rows:", len(dup))
print(dup[dup["company_id"] == "ADANIPORTS"])

Duplicate rows: 26
     id  company_id      year  sales  expenses  operating_profit  \
47  120  ADANIPORTS  Mar 2013   3577      1195            2382.0
48  121  ADANIPORTS  Mar 2014   4830      1910            2919.0
49  122  ADANIPORTS  Mar 2015   6152      2250            3902.0
50  123  ADANIPORTS  Mar 2016   7109      2532            4577.0
51  124  ADANIPORTS  Mar 2017   8439      3021            5418.0
52  125  ADANIPORTS  Mar 2018  11323      4166            7157.0
53  126  ADANIPORTS  Mar 2019  10925      4330            6596.0
54  127  ADANIPORTS  Mar 2020  11873      5926            5947.0
55  128  ADANIPORTS  Mar 2021  12550      3862            8688.0
56  129  ADANIPORTS  Mar 2022  17119      7591            9528.0
57  130  ADANIPORTS  Mar 2023  20852      9905           10947.0
58  131  ADANIPORTS  Mar 2024  26711     11121           15589.0
59  132  ADANIPORTS       TTM  28443     11278           17165.0
60  133  ADANIPORTS  Mar 2013   3577      1195            2382.0
61  134  ADANIPORTS  Mar 2014   4830      1910            2919.0
62  135  ADANIPORTS  Mar 2015   6152      2250            3902.0
63  136  ADANIPORTS  Mar 2016   7109      2532            4577.0
64  137  ADANIPORTS  Mar 2017   8439      3021            5418.0
65  138  ADANIPORTS  Mar 2018  11323      4166            7157.0
66  139  ADANIPORTS  Mar 2019  10925      4330            6596.0
67  140  ADANIPORTS  Mar 2020  11873      5926            5947.0
68  141  ADANIPORTS  Mar 2021  12550      3862            8688.0
69  142  ADANIPORTS  Mar 2022  17119      7591            9528.0
70  143  ADANIPORTS  Mar 2023  20852      9905           10947.0
71  144  ADANIPORTS  Mar 2024  26711     11121           15589.0
72  145  ADANIPORTS       TTM  28443     11278           17165.0

    opm_percentage  other_income  interest  depreciation  profit_before_tax  \
47            67.0           344       542           422               1762
48            60.0           685       977           649               1978
49            63.0           686      1175           912               2501
50            64.0           730      1124          1063               3119
51            64.0          1037      1116          1160               4179
52            63.0           844      1579          1188               5234
53            60.0          1289      1385          1373               5126
54            50.0          1928      1951          1680               4244
55            69.0          1967      2255          2107               6292
56            56.0          1832      2544          3099               5717
57            52.0           327      2363          3425               5487
58            58.0           671      2733          3888               9639
59            60.0          1039      2591          4053              11560
60            67.0           344       542           422               1762
61            60.0           685       977           649               1978
62            63.0           686      1175           912               2501
63            64.0           730      1124          1063               3119
64            64.0          1037      1116          1160               4179
65            63.0           844      1579          1188               5234
66            60.0          1289      1385          1373               5126
67            50.0          1928      1951          1680               4244
68            69.0          1967      2255          2107               6292
69            56.0          1832      2544          3099               5717
70            52.0           327      2363          3425               5487
71            58.0           671      2733          3888               9639
72            60.0          1039      2591          4053              11560

    tax_percentage  net_profit   eps  dividend_payout
47             7.0        1639   8.0             12.0
48            12.0        1741   8.0             12.0
49             7.0        2324  11.0             10.0
50             9.0        2856  14.0              8.0
51             7.0        3902  19.0              7.0
52            30.0        3690  18.0             11.0
53            21.0        4045  19.0              1.0
54            11.0        3785  19.0             17.0
55            20.0        5049  25.0             20.0
56            13.0        4953  23.0             22.0
57             2.0        5391  25.0             20.0
58            16.0        8104  38.0             16.0
59             NaN        9743  45.0              NaN
60             7.0        1639   8.0             12.0
61            12.0        1741   8.0             12.0
62             7.0        2324  11.0             10.0
63             9.0        2856  14.0              8.0
64             7.0        3902  19.0              7.0
65            30.0        3690  18.0             11.0
66            21.0        4045  19.0              1.0
67            11.0        3785  19.0             17.0
68            20.0        5049  25.0             20.0
69            13.0        4953  23.0             22.0
70             2.0        5391  25.0             20.0
71            16.0        8104  38.0             16.0
72             NaN        9743  45.0              NaN

In [4]:
docs = pd.read_excel("../data/raw/documents.xlsx", header=1)
print(docs.columns.tolist())
print(docs.head(3))

['id', 'company_id', 'Year', 'Annual_Report']
   id company_id  Year                                      Annual_Report
0   1        ABB  2024  https://www.bseindia.com/xml-data/corpfiling/A...
1   2        ABB  2023  https://www.bseindia.com/xml-data/corpfiling/A...
2   3        ABB  2022  https://www.bseindia.com/bseplus/AnnualReport/...

In [6]:
analysis = pd.read_excel("../data/raw/analysis.xlsx", header=1)
print(analysis.columns.tolist())
print(analysis.head(3))

['id', 'company_id', 'compounded_sales_growth', 'compounded_profit_growth', 'stock_price_cagr', 'roe']
   id company_id compounded_sales_growth compounded_profit_growth  \
0   1   HDFCBANK           10 Years: 21%            10 Years: 22%
1  10    SBILIFE      5 Years:       24%   5 Years:            6%
2  11    SBILIFE      3 Years:       17%   3 Years:            9%

         stock_price_cagr                   roe
0       10 Years:     15%     10 Years:     17%
1       5 Years:       8%  5 Years          14%
2       3 Years:       7%  3 Years:         13%

In [8]:
companies = pd.read_excel("../data/raw/companies.xlsx", header=1)
print(companies[["id", "company_name"]].head())
print("rows:", len(companies))

           id                               company_name
0         ABB                           Abbott India Ltd
1  ADANIENSOL                 Adani Energy Solutions Ltd
2    ADANIENT                      Adani Enterprises Ltd
3  ADANIGREEN                     Adani Green Energy Ltd
4  ADANIPORTS  Adani Ports & Special Economic Zone Ltd\n
rows: 92

In [12]:
files = [
    "financial_ratios.xlsx",
    "stock_prices.xlsx",
    "market_cap.xlsx",
    "peer_groups.xlsx"
]

for file in files:
    df = pd.read_excel(f"../data/supporting/{file}")
    print("\n", file)
    print(df.columns.tolist())
    print(df.head(3))

 financial_ratios.xlsx
['id', 'company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr']
   id company_id      year  net_profit_margin_pct  \
0   1        ABB  Dec 2012                   8.77
1   2        ABB  Mar 2014                   8.70
2   3        ABB  Mar 2014                   8.70

   operating_profit_margin_pct  return_on_equity_pct  debt_to_equity  \
0                         12.0                 22.41             0.0
1                         12.0                 25.13             0.0
2                         12.0                 25.13             0.0

   interest_coverage  asset_turnover  free_cash_flow_cr  capex_cr  \
0                NaN          1.8225               42.0      59.0
1                NaN          1.9982               11.0     144.0
2                NaN          1.9982                0.0       0.0

   earnings_per_share  book_value_per_share  dividend_payout_ratio_pct  \
0                68.0                3.0810                       25.0
1                93.0                3.7524                       25.0
2                93.0                3.7524                       25.0

   total_debt_cr  cash_from_operations_cr
0              0                    101.0
1              0                    155.0
2              0                      0.0

 stock_prices.xlsx
['id', 'company_id', 'date', 'open_price', 'high_price', 'low_price', 'close_price', 'volume', 'adjusted_close']
   id company_id        date  open_price  high_price  low_price  close_price  \
0   1        ABB  2020-01-01     1958.61     2150.53    1835.28      1964.30
1   2        ABB  2020-02-01     2177.03     2192.92    1931.08      2165.21
2   3        ABB  2020-03-01     2221.26     2440.28    1995.23      2198.78

     volume  adjusted_close
0  26184368         1964.30
1   1668316         2165.21
2  20578107         2198.78

 market_cap.xlsx
['id', 'company_id', 'year', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct']
   id company_id  year  market_cap_crore  enterprise_value_crore  pe_ratio  \
0   1        ABB  2019         844312.98               814410.48     19.29
1   2        ABB  2020         923674.33              1120679.72     67.54
2   3        ABB  2021        1020674.09              1166450.81     62.63

   pb_ratio  ev_ebitda  dividend_yield_pct
0     14.26      22.84                0.84
1     13.03      24.93                3.90
2      6.67       7.58                1.58

 peer_groups.xlsx
['id', 'peer_group_name', 'company_id', 'is_benchmark']
   id peer_group_name company_id  is_benchmark
0   1   Private Banks   HDFCBANK          True
1   2   Private Banks  ICICIBANK         False
2   3   Private Banks   AXISBANK         False

In [13]:
df = pd.read_excel("../data/supporting/sectors.xlsx")
print(df.columns.tolist())
print(df.head(5))
print(df.shape)

['id', 'company_id', 'broad_sector', 'sub_sector', 'index_weight_pct', 'market_cap_category']
   id  company_id broad_sector         sub_sector  index_weight_pct  \
0   1         ABB  Industrials      Capital Goods              0.81
1   2  ADANIENSOL       Energy  Power & Utilities              0.65
2   3    ADANIENT  Industrials      Conglomerates              1.50
3   4  ADANIGREEN       Energy   Renewable Energy              1.23
4   5  ADANIPORTS  Industrials     Infrastructure              2.12

  market_cap_category
0           Large Cap
1           Large Cap
2           Large Cap
3           Large Cap
4           Large Cap
(92, 6)

In [15]:
import re
import pandas as pd


def normalize_ticker(value):
    if value is None:
        return None

    value = str(value).strip().upper()
    value = value.replace(".NS", "")
    value = value.replace(".BO", "")
    value = value.replace("\n", "")
    value = value.replace("\t", "")
    value = re.sub(r"\s+", "", value)

    return value


companies = pd.read_excel("../data/raw/companies.xlsx", header=1)
companies["id"] = companies["id"].apply(normalize_ticker)
valid_ids = set(companies["id"].dropna())

tables = {
    "profitandloss": pd.read_excel("../data/raw/profitandloss.xlsx", header=1),
    "balancesheet": pd.read_excel("../data/raw/balancesheet.xlsx", header=1),
    "cashflow": pd.read_excel("../data/raw/cashflow.xlsx", header=1),
    "analysis": pd.read_excel("../data/raw/analysis.xlsx", header=1),
    "documents": pd.read_excel("../data/raw/documents.xlsx", header=1),
    "prosandcons": pd.read_excel("../data/raw/prosandcons.xlsx", header=1),
    "financial_ratios": pd.read_excel("../data/supporting/financial_ratios.xlsx"),
}

for name, df in tables.items():
    df["company_id_norm"] = df["company_id"].apply(normalize_ticker)
    invalid = sorted(set(df["company_id_norm"].dropna()) - valid_ids)

    print(f"\n{name}")
    print("invalid company ids count:", len(invalid))
    print(invalid[:50])

profitandloss
invalid company ids count: 8
['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

balancesheet
invalid company ids count: 7
['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

cashflow
invalid company ids count: 9
['AGTL', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

analysis
invalid company ids count: 1
['WIPRO']

documents
invalid company ids count: 8
['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

prosandcons
invalid company ids count: 1
['WIPRO']

financial_ratios
invalid company ids count: 2
['ULTRACEMCO', 'UNIONBANK']

In [16]:
companies = pd.read_excel("../data/raw/companies.xlsx", header=1)
companies["id"] = companies["id"].apply(normalize_ticker)

# search for suspected companies by name
keywords = [
    "ULTRA", "UNION", "UNITED", "VARUN", "VEDANTA",
    "WIPRO", "ZOMATO", "ZYDUS", "ADANI TOTAL"
]

for kw in keywords:
    print(f"\n--- {kw} ---")
    print(companies[companies["company_name"].str.upper().str.contains(kw, na=False)][["id", "company_name"]])

--- ULTRA ---
Empty DataFrame
Columns: [id, company_name]
Index: []

--- UNION ---
Empty DataFrame
Columns: [id, company_name]
Index: []

--- UNITED ---
Empty DataFrame
Columns: [id, company_name]
Index: []

--- VARUN ---
Empty DataFrame
Columns: [id, company_name]
Index: []

--- VEDANTA ---
Empty DataFrame
Columns: [id, company_name]
Index: []

--- WIPRO ---
Empty DataFrame
Columns: [id, company_name]
Index: []

--- ZOMATO ---
Empty DataFrame
Columns: [id, company_name]
Index: []

--- ZYDUS ---
Empty DataFrame
Columns: [id, company_name]
Index: []

--- ADANI TOTAL ---
     id         company_name
9  ATGL  Adani Total Gas Ltd

In [17]:
import sqlite3
conn = sqlite3.connect("../nifty100.db")

In [18]:
review_companies = pd.read_sql("""
SELECT id, company_name
FROM companies
ORDER BY id
LIMIT 5;
""", conn)

review_companies

           id                               company_name
0         ABB                           Abbott India Ltd
1  ADANIENSOL                 Adani Energy Solutions Ltd
2    ADANIENT                      Adani Enterprises Ltd
3  ADANIGREEN                     Adani Green Energy Ltd
4  ADANIPORTS  Adani Ports & Special Economic Zone Ltd\n

In [19]:
query = """
SELECT 
    c.id,
    c.company_name,

    (SELECT COUNT(*) FROM profitandloss p WHERE p.company_id = c.id) AS pnl_years,
    (SELECT COUNT(*) FROM balancesheet b WHERE b.company_id = c.id) AS bs_years,
    (SELECT COUNT(*) FROM cashflow cf WHERE cf.company_id = c.id) AS cf_years,
    (SELECT COUNT(*) FROM documents d WHERE d.company_id = c.id) AS document_count

FROM companies c
WHERE c.id IN ({})
ORDER BY c.id;
""".format(",".join([f"'{cid}'" for cid in review_companies["id"].tolist()]))

coverage_df = pd.read_sql(query, conn)
coverage_df

,id,company_name,pnl_years,bs_years,cf_years,document_count
0,ABB,Abbott India Ltd,12,12,12,16
1,ADANIENSOL,Adani Energy Solutions Ltd,11,11,11,16
2,ADANIENT,Adani Enterprises Ltd,12,12,12,16
3,ADANIGREEN,Adani Green Energy Ltd,8,8,8,16
4,ADANIPORTS,Adani Ports & Special Economic Zone Ltd\n,12,12,12,16

In [20]:
less_than_5 = pd.read_sql("""
SELECT 
    c.id,
    c.company_name,
    COALESCE(p.pnl_years, 0) AS pnl_years,
    COALESCE(b.bs_years, 0) AS bs_years,
    COALESCE(cf.cf_years, 0) AS cf_years
FROM companies c
LEFT JOIN (
    SELECT company_id, COUNT(*) AS pnl_years
    FROM profitandloss
    GROUP BY company_id
) p ON c.id = p.company_id
LEFT JOIN (
    SELECT company_id, COUNT(*) AS bs_years
    FROM balancesheet
    GROUP BY company_id
) b ON c.id = b.company_id
LEFT JOIN (
    SELECT company_id, COUNT(*) AS cf_years
    FROM cashflow
    GROUP BY company_id
) cf ON c.id = cf.company_id
WHERE COALESCE(p.pnl_years, 0) < 5
   OR COALESCE(b.bs_years, 0) < 5
   OR COALESCE(cf.cf_years, 0) < 5
ORDER BY c.id;
""", conn)

less_than_5

       id                company_name  pnl_years  bs_years  cf_years
0    ATGL         Adani Total Gas Ltd          7         7         0
1  JIOFIN  Jio Financial Services Ltd          2         2         2
2    SBIN         State Bank of India         12         0        12

In [21]:
pnl_raw = pd.read_excel("../data/raw/profitandloss.xlsx", header=1)
bs_raw = pd.read_excel("../data/raw/balancesheet.xlsx", header=1)
cf_raw = pd.read_excel("../data/raw/cashflow.xlsx", header=1)

flagged_ids = ["ATGL", "AGTL", "JIOFIN", "SBIN"]

for cid in flagged_ids:
    print(f"\n================ {cid} ================")

    pnl_rows = pnl_raw[pnl_raw["company_id"].astype(str).str.upper() == cid]
    bs_rows = bs_raw[bs_raw["company_id"].astype(str).str.upper() == cid]
    cf_rows = cf_raw[cf_raw["company_id"].astype(str).str.upper() == cid]

    print("P&L rows:", len(pnl_rows))
    if len(pnl_rows) > 0:
        print(pnl_rows[["company_id", "year"]].head(10))

    print("BS rows:", len(bs_rows))
    if len(bs_rows) > 0:
        print(bs_rows[["company_id", "year"]].head(10))

    print("CF rows:", len(cf_rows))
    if len(cf_rows) > 0:
        print(cf_rows[["company_id", "year"]].head(10))

================ ATGL ================
P&L rows: 8
    company_id      year
125       ATGL  Mar 2018
126       ATGL  Mar 2019
127       ATGL  Mar 2020
128       ATGL  Mar 2021
129       ATGL  Mar 2022
130       ATGL  Mar 2023
131       ATGL  Mar 2024
132       ATGL       TTM
BS rows: 8
    company_id      year
125       ATGL  Mar 2018
126       ATGL  Mar 2019
127       ATGL  Mar 2020
128       ATGL  Mar 2021
129       ATGL  Mar 2022
130       ATGL  Mar 2023
131       ATGL  Mar 2024
132       ATGL  Sep 2024
CF rows: 0

================ AGTL ================
P&L rows: 0
BS rows: 0
CF rows: 7
    company_id      year
126       AGTL  Mar 2018
127       AGTL  Mar 2019
128       AGTL  Mar 2020
129       AGTL  Mar 2021
130       AGTL  Mar 2022
131       AGTL  Mar 2023
132       AGTL  Mar 2024

================ JIOFIN ================
P&L rows: 3
    company_id      year
687     JIOFIN  Mar 2023
688     JIOFIN  Mar 2024
689     JIOFIN       TTM
BS rows: 3
    company_id      year
866     JIOFIN  Mar 2023
867     JIOFIN  Mar 2024
868     JIOFIN  Sep 2024
CF rows: 2
    company_id      year
661     JIOFIN  Mar 2023
662     JIOFIN  Mar 2024

================ SBIN ================
P&L rows: 13
    company_id      year
970       SBIN  Mar 2013
971       SBIN  Mar 2014
972       SBIN  Mar 2015
973       SBIN  Mar 2016
974       SBIN  Mar 2017
975       SBIN  Mar 2018
976       SBIN  Mar 2019
977       SBIN  Mar 2020
978       SBIN  Mar 2021
979       SBIN  Mar 2022
BS rows: 0
CF rows: 12
    company_id      year
918       SBIN  Mar 2013
919       SBIN  Mar 2014
920       SBIN  Mar 2015
921       SBIN  Mar 2016
922       SBIN  Mar 2017
923       SBIN  Mar 2018
924       SBIN  Mar 2019
925       SBIN  Mar 2020
926       SBIN  Mar 2021
927       SBIN  Mar 2022

In [22]:
conn.close()